name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest"
          #   args: "--target aarch64-apple-darwin"
          # - platform: "macos-latest"
          #   args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          # - platform: "windows-latest"
          #   args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # Install System Dependencies (The most important part!)
      - name: install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo add-apt-repository ppa:alex-p/tesseract-ocr5 -y
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            g++ \
            pkg-config \
            libtesseract-dev \
            libleptonica-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff-dev \
            clang \
            libclang-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            javascriptcoregtk-4.1-dev \
            xdg-utils

      - name: install dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: brew install tesseract

      - name: install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: vcpkg install tesseract:x64-windows-static

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install pnpm
        run: npm install -g pnpm

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.TAURI_RELEASE_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
